changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Important Changes
      labels:
        - "Changelog: Important Change"
    - title: Breaking Changes
      labels:
        - "Changelog: Breaking Change"
      commit_patterns:
        - "^(?<type>\\w+(?:\\((?<scope>[^)]+)\\))?!:\\s*)"
    
    - title: Features
      labels:
        - "Changelog: Feature"
      commit_patterns:
        - "^(?<type>feat(?:\\((?<scope>[^)]+)\\))?!?:\\s*)"
    
    - title: Bug Fixes
      labels:
        - "Changelog: Bugfix"
      commit_patterns:
        - "^(?<type>fix(?:\\((?<scope>[^)]+)\\))?!?:\\s*)"
        - "^Revert \""
    
    - title: Documentation
      labels:
        - "Changelog: Docs"
      commit_patterns:
        - "^(?<type>docs?(?:\\((?<scope>[^)]+)\\))?!?:\\s*)"
  
    - title: Internal Changes
      labels:
        - "Changelog: Internal"
      commit_patterns:
        - "^(?<type>(?:build|refactor|meta|chore|ci|ref|perf)(?:\\((?<scope>[^)]+)\\))?!?:\\s*)"