minVersion: 0.23.1
changelogPolicy: simple
preReleaseCommand: bash scripts/craft-pre-release.sh
targets:
  - name: npm
  - name: registry
    apps:
      app:sentry-wizard:
        name: registry
        urlTemplate: https://github.com/getsentry/sentry-wizard/releases/tag/v{{version}}
  - name: github
    tagPrefix: v
